### ISSUE TITLE
Stop widgets resizing stretched layer surface

### ISSUE THREAD

**Issue by ammen99** [wmww/gtk-layer-shell#11]
I have a panel which I am trying to port to gtk-layer-shell. However it contains some widgets which adapt their size based on the size of the panel, and hence I need to know the configure size in order to set the correct size for the whole panel (the story is a bit longer, but not relevant here).

So I'd ideally need a way to get the size the compositor sends with the configure() event. How can I achieve this?

**Comment by wmww** [comment]
When the compositor configures a layer surface, gtk-layer-shell calls `gtk_window_resize()`. This should trigger a `size-allocate` event on the `GtkWindow` (which I think should also result in `size-allocate` getting called for children, depending on the logic of the containers they're in). Does that answer your question?

**Comment by ammen99** [comment]
Sadly no, because I cannot distinguish `size-allocate` in response to `window_resize()` and `size-allocate` in response to widget changing size.

**Comment by wmww** [comment]
Hmm..

**Comment by wmww** [comment]
A layer surface window should act just like a maximized window with respect to sizing. A widget can't force a maximized window to resize, and a child *should* not be able to force a layer surface window to resize along an axis it is anchored to both sides of.

I'm real busy atm, so I can't help as much as I'd like. Good luck.

**Comment by ammen99** [comment]
Well sadly this is not the case. I can see that the window resizes itself to a smaller size than the width of the output (panel is anchored to top,left and right edges, and the compositor sends only full-width configures). I think this is because GTK usually tries to make the window as small as possible. Maybe we can set the size request?

**Comment by ammen99** [comment]
Hmm, this fixes my problem: http://ix.io/1RQC

Do you think this is the correct solution? I will send it as a PR if you think this is acceptable.

**Comment by wmww** [comment]
No, that has issues.
1. Run gtk-layer-demo
2. Expand the surface
3. Anchor it
It should shrink, but it doesn't. I wrote a longer, fancier version of the function (below) that *should* have fixed it, but didn't. You can try fiddling with it, but if you just use your patch for now I'll figure it out this weekend.

```c
static void
layer_surface_handle_configure (void *data,
                                struct zwlr_layer_surface_v1 *surface,
                                uint32_t serial,
                                uint32_t w,
                                uint32_t h)
{
    LayerSurface *self = data;

    gint width = (w == 0 ? -1 : (gint)w);
    gint height = (h == 0 ? -1 : (gint)h);
    GtkWindow *gtk_window = custom_shell_surface_get_gtk_window ((CustomShellSurface *)self);
    gtk_widget_set_size_request (GTK_WIDGET (gtk_window), width, height);

    if (width > 0 || height > 0) {
        if (width <= 0 || height <= 0)
        {
            GtkRequisition current_size = layer_surface_get_gtk_window_size (self);
            if (width <= 0)
                width = current_size.width;
            if (height <= 0)
                height = current_size.height;
        }
        gtk_window_resize (gtk_window, width, height);
    }

    zwlr_layer_surface_v1_ack_configure (surface, serial);
}
```

**Comment by ammen99** [comment]
I tried to fiddle around a bit more, but I am not sure how to fix the issue.

Some random thoughts: It makes sense to propagate the configure event to the program. For example, a panel or similar may want to have only half the width/height of the screen. It could anchor itself to 3 edges and configure its size as it wants.

Maybe we could have a signal whose handlers return a bool indicating whether the client wants to set its size manually or not? I think GTK has such behavior for a lot of events.

Note: I do not actually care about the use-case above yet, so if you think it is overcomplicating things or out-of-scope for gtk-layer-shell, I would be happy with just setting the size request (the natural height may be less than the full width, so we do need to increase it).

**Comment by wmww** [comment]
I thought about it, but I want to keep the gtk-layer-shell's API as simple as possible. I'd consider that only if there was a real-word use case that required it. I think the standard GTK resizing system should be able to handle what we want.
