### ISSUE TITLE
Some errors with gtk 3.24.26

### ISSUE THREAD

**Issue by charlie39** [wmww/gtk-layer-shell#113]
Arch linux is on gtk 3.24.30 and perhaps that's why such [issues](https://github.com/Alexays/Waybar/issues/1280) are being reported. I am facing this [issue](https://github.com/Alexays/Waybar/issues/1280) and also someone else reported the same there.
So i build version 3.24.26 with the old version of [PKGBUILD](https://github.com/archlinux/svntogit-packages/commit/3d0aff9f449cf7a14687035b5a2aee74f526568b#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a) . And now i am getting 
```
Gdk-Message: 01:27:01.209: Error 2 (No such file or directory) dispatching to Wayland display.
```
.  I get this while launching waybar which uses gtk layer shell. Just reporting
This is the  output of  ``` waybar -l trace ```

```
[2021-11-03 01:28:49.574] [debug] GTK widget tree:
window#waybar.background.eDP-1.:dir(ltr)
  decoration:dir(ltr)
  box.horizontal:dir(ltr)
    box.horizontal.modules-left:dir(ltr)
      widget:dir(ltr)
        box#tags.horizontal:dir(ltr)
          button.flat.text-button:dir(ltr)
            label:dir(ltr)
          button.flat.text-button:dir(ltr)
            label:dir(ltr)
          button.flat.text-button:dir(ltr)
            label:dir(ltr)
          button.flat.text-button:dir(ltr)
            label:dir(ltr)
          button.flat.text-button:dir(ltr)
            label:dir(ltr)
    box.horizontal.modules-center:dir(ltr)
    box.horizontal.modules-right:dir(ltr)
      widget:dir(ltr)
        label#mpd:dir(ltr)
      widget:dir(ltr)
        label#pulseaudio:dir(ltr)
      widget:dir(ltr)
        label#network:dir(ltr)
      widget:dir(ltr)
        label#cpu:dir(ltr)
      widget:dir(ltr)
        label#memory:dir(ltr)
      widget:dir(ltr)
        label#temperature:dir(ltr)
      widget:dir(ltr)
        label#backlight:dir(ltr)
      widget:dir(ltr)
        label#battery:dir(ltr)
      widget:dir(ltr)
        label#clock:dir(ltr)

Gdk-Message: 01:28:49.574: Error 2 (No such file or directory) dispatching to Wayland display.
```
This seems related to gtk layer shell and gtk so reporting here

**Comment by wmww** [comment]
Need to release a new version with official support for GTK 3.24.30, but I doubt that;s the problem. `gtk-layer-demo` doesn't have any problems for me. I tried to build Waybar to reproduce, but hit https://github.com/Alexays/Waybar/issues/1306.

**Comment by charlie39** [comment]
@wmww I wanted to get to the bottom of the 'incompatibilies' between gtk layer shell and gtk as you mentioned in the compatibility.md 
What is the underlying problem that requires gtk layer shell to hack around to make it compatible with gtk ?
I am not into gtk programming but use some tools to depends on it and I wanted to read about if there's any docs you can refer. Why can't gtk make it smooth for gtk layer shell ? Is not one of those standard protocol ? What do others use instead of gtk layer shell ? Is gtk-layer-shell an alternative to xdg-deskyop-portal?

**Comment by charlie39** [comment]
> ... The GNOME/GTK devs are generally of the opinion that these things should be provided by the shell ...

By shell they mean a GUI shell like gnome shell I assume. So is this why this only concerns with those who doesn't use a GUI shell , like the standalone window manager put there. Is that correct ?


Yes the waybar issue seems to be with their official release. The git version from AUR is working fine , thanks

**Comment by charlie39** [comment]
Also,  what would be the equivalent of layer shell in X ? Or is this something new in Wayland ?

**Comment by wmww** [comment]
> By shell they mean a GUI shell like gnome shell I assume. So is this why this only concerns with those who doesn't use a GUI shell , like the standalone window manager put there. Is that correct ?

Yes

> Also, what would be the equivalent of layer shell in X ? Or is this something new in Wayland ?

I believe there's something called struts in X11 which can be used to accomplish a similar thing. An app would need to link to an X11 library, and implementing the behavior would probably be more complicated than using GTK Layer Shell.
