### ISSUE TITLE
bug transparancy

### ISSUE THREAD

**Issue by hydrasho** [wmww/gtk-layer-shell#117]
it is impossible to assign alpha values to gtk-layer-shell widgets. example:

create a window with rgba(250,0,0,1);
will create a completely opaque window however
if I put rgba(250,0,0,0); it will create a completely transparent window! This shows that layershell is compatible with transparency and that it is probably a bug.

There is also the fact that my compositor can't blur the transparent widget created by layershell. (But I think it's the same problem)

Translated with www.DeepL.com/Translator (free version)

**Comment by ErikReider** [comment]
I just set the windows `background` to `rgba(0, 0, 0, 0,5)` through CSS

**Comment by hydrasho** [comment]
Ah yes... but normally the css is from 0 to 255 not 0.5 on widgets out of layershell but it doesn't matter, it works! 

so there is still the problem with the fact that the composer doesn't put blur on transparent widgets when they are on layer shell

**Comment by hydrasho** [comment]
![Snapchat-509096971](https://user-images.githubusercontent.com/40312793/148274852-69bb6a40-d07a-48c7-a7e4-2783686a9fb2.jpg)
with layer shell

![Snapchat-1002030121](https://user-images.githubusercontent.com/40312793/148274882-d2e9e0a6-6242-46ce-a9d3-3b9b8a32d6fd.jpg)
 without layershell

**Comment by ErikReider** [comment]
> Ah yes... but normally the css is from 0 to 255 not 0.5 on widgets out of layershell but it doesn't matter, it works!

The first 3 are R,G,B which can be from 0 to 255 while the last one stands for Alpha which goes from 0 to 1

[Mozilla CSS doc](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgba())

**Comment by hydrasho** [comment]
okay I see so it's GtK who made a mistake so for the CSS I'll take it.

for the blur I have to ask wayfire or it comes from layershell?

**Comment by ErikReider** [comment]
I'm not familiar with the layer shell code so I don't know. Hopefully somebody else does :)

**Comment by ammen99** [comment]
The blur comes from Wayfire. You probably have not set up all surfaces to be blurred, see https://github.com/WayfireWM/wayfire/issues/1399 for a similar issue and a solution which should work for you.

**Comment by hydrasho** [comment]
thank, i close this :)
