### ISSUE TITLE
How to use Gtk layer shell with gtkmm (the c++ binding)

### ISSUE THREAD

**Issue by hamza-Algohary** [wmww/gtk-layer-shell#123]
I want to write an app in c++ with gtkmm3 and layershell.
I want to know if there is c++ binding for Gtk layer shell, or is there a possible way to use the C API with gtkmm API.

Thanks in advance. And also big thanks for your work.

**Comment by wmww** [comment]
I imagine it should be possible to use the C++ API to access the underlying C GTK objects and use gtk-layer-shell with those. It may also be possible to generate C++ API for gtk-layer-shell using the GIR. I'm not familiar with gtkmm though, so I can't give further details.
