### ISSUE TITLE
GTK-compatibility needs to be raised!

### ISSUE THREAD

**Issue by Nonie689** [wmww/gtk-layer-shell#126]
[compatibility.md](https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md)

I get crashes when I try to run wf-panel.

** (wf-panel:338773): WARNING **: 02:36:22.102: gtk-layer-shell v0.7.0 may not work on GTK v3.24.34. If you experience crashes, check https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md

**Comment by wmww** [comment]
There have been no relevant changes to GTK since v0.7.0 was released. I also just manually tested and v0.7.0 works fine with GTK v3.24.34. Updated compat doc to reflect that. Crash is likely a wf-panel bug.
