### ISSUE TITLE
Namespace shouldn't overlap Gtk

### ISSUE THREAD

**Issue by TingPing** [wmww/gtk-layer-shell#13]
I realize this isn't a high priority issue but you should never use the namespace of another library in your namespace. This is a mistake other libraries have made (GtkSourceView) and isn't something to be duplicated.

A random idea would be to use `gls_` (`Gls`) for the namespace.

**Comment by wmww** [comment]
Ack. I'll keep that in mind, but it probably won't make sense to fix until there is a completely breaking change (such as moving to GTK4).
