### ISSUE TITLE
Pointer constraints do not seem to be compatible with gtk-layer-shell

### ISSUE THREAD

**Issue by Tamaranch** [wmww/gtk-layer-shell#132]
gtk-layer-shell 0.7.0 and git-master.

I use Labwc as a compositor, where [pointer constraints](https://wayland.app/protocols/pointer-constraints-unstable-v1) work correctly (in my case `zwp_confined_pointer_v1`). But calling `gtk_layer_init_for_window()` seems to prevent them from taking effect. There is no error message, but the "confined" signal handler is never called, and in fact the pointer is not confined.

Is this a known problem? Is there a workaround? Thanks.

**Comment by wmww** [comment]
Can you please provide minimal sample code that reproduces the issue?

**Comment by Tamaranch** [comment]
Sorry, I got confused in my tests. Pointer constraints without layer shell work correctly on Weston, not on Labwc (the "confined" signal handler is called, but the pointer is not actually confined). And they work correctly with and without layer shell for example on Wayfire. So the problem seems to come from Labwc.

I'll investigate a bit before opening an issue on Labwc, I'll link it here if I open it. Sorry for the noise.

**Comment by Tamaranch** [comment]
Labwc issue: https://github.com/labwc/labwc/issues/475
