### ISSUE TITLE
New release for VAPI

### ISSUE THREAD

**Issue by RossComputerGuy** [wmww/gtk-layer-shell#136]
Hello, I am wondering when we will have a new release. I would like to see the VAPI file be packages in nixOS and they won't update the package until there is a new release. https://github.com/NixOS/nixpkgs/issues/196173 depends on this issue.

**Comment by wmww** [comment]
It's been a while, I'll roll one today. Is everything currently merged good to go for your usecase?

**Comment by RossComputerGuy** [comment]
Yes, there's no more PR's that can be merged so an 0.8.0 release would be nice. However, it would also be great to have gtk3 `3.24.34` support. I tried using gtk-layer-shell from source and got a version warning.

**Comment by wmww** [comment]
Thanks for being patient. v0.8.0 has now been released with the VAPI stuff and explicit GTK 3.24.34 support. Enjoy!
