### ISSUE TITLE
Background layer does not work under Sway

### ISSUE THREAD

**Issue by RossComputerGuy** [wmww/gtk-layer-shell#140]
When using the background layer in my code, the window never render but if I use the bottom layer then it does but renders above other windows. [This](https://github.com/ExpidusOS/genesis/blob/51e605c06df8e5f4c89dee9bcbc1e2e045343c7d/plugins/gtk3/src/windows/desktop.vala#L88-L105) is my Vala code and I am unsure what I am doing wrong or if this is a bug. The demo works fine with using the background layer so this is a strange bug.

**Comment by ErikReider** [comment]
Probably rendering behind your wallpaper

**Comment by RossComputerGuy** [comment]
Sweet, that worked. Not sure why the demo worked but not my code without killing `swaybg`.

**Comment by RossComputerGuy** [comment]
Now, I might need help with the [panel window code](https://github.com/ExpidusOS/genesis/blob/refactor/plugins/gtk3/src/windows/panel.vala). I can't use any windows, may be because of the margins. If I set the bottom margin to `this.monitor.mode.height - 5` then Sway crashes. Also, the background doesn't render behind the panel.

**Comment by Consolatis** [comment]
Sorry for the off-topic:

> If I set the bottom margin to this.monitor.mode.height - 5 then Sway crashes

If you manage to actually crash sway with a layer-shell application using negative margins an issue at https://github.com/swaywm/sway would be nice.

**Comment by RossComputerGuy** [comment]
`this.monitor.mode.height - 5` is `1440 - 5` on my system.
