### ISSUE TITLE
sway < 1.2 compatibility

### ISSUE THREAD

**Issue by alebastr** [wmww/gtk-layer-shell#16]
Last time I tried, sway without layer-shell popups patch did not display popups/tooltips/select boxes at all.
Is it possible to detect that sway is unable to create popup and provide graceful fallback to gtk default behavior (i.e. do nothing and expect gtk to create xdg_toplevel)? I'd accept the manual switch api as well, because with the current behavior I have to conditionally compile raw zwlr_layer_surface_* code for older versions of sway.

**Comment by wmww** [comment]
While this is probably possible, its not worth the added complexity to the code. I consider supporting fallback paths for broken compositors definitively out of scope.
