### ISSUE TITLE
Do exclusive zones work if the window in question has a margin?

### ISSUE THREAD

**Issue by spl237** [wmww/gtk-layer-shell#168]
I'm doing some work with setting margins and anchors on a panel to space it from the sides of the screen, and it seems to make the exclusive zone set for the panel behave oddly.

I have auto_exclusive_zone_enable set for a panel. If I anchor it to the top or the bottom of the screen with no margin, it seems to work correctly, pushing other windows down or up as expected.

But if I set both an anchor and a margin, it doesn't seem to work, or at least not in a consistent fashion; I get different behaviour at top and bottom of the screen, for a start.

Before I do any more investigation, is it just that exclusive zones are not intended to work for windows which have both a margin and an anchor set, and will only work if the window is directly anchored to an edge without a margin?

**Comment by wmww** [comment]
Hey, sorry for the wait. Then intention of the API is that (when auto exclusive zones are used) margin can be used to control the size of the exclusive zone to be bigger or smaller than the surface. Play around with `gtk4-layer-demo` to see exactly how it works.
