### ISSUE TITLE
Modifiers not reported in click events after using gtk_layer_init_for_window()

### ISSUE THREAD

**Issue by Tamaranch** [wmww/gtk-layer-shell#175]
Not sure why I didn't report this already, as I'd noticed it for a while on xfce4-panel, or it's already been discussed somewhere and I can't remember. Anyway it's easily reproducible: after applying `gtk_layer_init_for_window()` on a GtkWindow, `event->state` is always zero in the "button-press-event" signal handler.

**Comment by wmww** [comment]
What keyboard interactivity mode is being used? If it's `none` this is not surprising, as the app doesn't have access to the keyboard.

**Comment by Tamaranch** [comment]
Indeed, it works in exclusive mode, but not always in on-demand mode, depending on the compositor. So I'm not in the right place.

I find it a bit odd that it depends on the keyboard interactivity mode, because we're talking about a click event, where the keyboard keys only intervene as modifiers of this event, not a key event. But then, I guess there's not much you can do about it, and it had to be discussed at the protocol level...
