### ISSUE TITLE
The window doesn't appear unless GTK_DEBUG=interactive is set

### ISSUE THREAD

**Issue by diniamo** [wmww/gtk-layer-shell#179]
The source code can be found at https://github.com/diniamo/bgar

I have no idea what information, other than the title, I could provide.

**Comment by Consolatis** [comment]
I assume it was fixed client side. Out of curiosity, what was the reason it didn't work before and how did you fix it?

**Comment by diniamo** [comment]
I wouldn't call it a fix.

Instead of passing `None` (I use the Rust bindings) or an empty string for the initial label, I passed a space.
