### ISSUE TITLE
Put a layer onto multiple monitors

### ISSUE THREAD

**Issue by DhruvaSambrani** [wmww/gtk-layer-shell#180]
`gtk_layer_set_monitor` allows us to request to change the monitor that the layer is placed onto. Is is possible to place a layer onto multiple monitors?

**Comment by ammen99** [comment]
Not the author of this library, but this shouldn't be possible because the underlying protocol does not allow it either.

**Comment by DhruvaSambrani** [comment]
I am absolutely new to Wayland dev, so I may be grossly wrong in this.

However, can we add this in the protocol?

**Comment by Consolatis** [comment]
You can add multiple surfaces, one per monitor.
