### ISSUE TITLE
gtk-priv update needed for upcoming GTK 3.24.44

### ISSUE THREAD

**Issue by alebastr** [wmww/gtk-layer-shell#187]
https://github.com/GNOME/gtk/commit/b8435aab3933d6173fbeb62e0c079d5680e25d53 in gtk-3-24 branch changes layout of `struct _GdkWindowImplWayland`.

A backport of the patch in Debian has shown that this breaks gtk-layer-shell (https://github.com/Alexays/Waybar/issues/3542), so we'll need a patch release with gtk-priv update by the time 3.24.44 is out.

**Comment by wmww** [comment]
Thanks for pointing out precisely what changed where, it helped me notice and debug an issue in the gtk-priv script that would have caused me to release without the new struct included.
