### ISSUE TITLE
Window size is too small

### ISSUE THREAD

**Issue by DemiMarie** [wmww/gtk-layer-shell#194]
I’m working on porting the [Qubes OS app menu][1] to use layer shell on Wayland.  It currently uses GTK3, and I’m not sure how hard it would be to port to GTK4.

It works great, except that the window height is too small, so not enough entries fit on the screen.  Is therw a way to improve it?  The same code produces a correctly-sized window under X11.

[1]: https://github.com/QubesOS/qubes-desktop-linux-menu

**Comment by wmww** [comment]
You can play around with [this](https://wmww.github.io/gtk-layer-shell/#Forcing-Window-Size) to see if you can make it work better.

**Comment by DemiMarie** [comment]
I actually got the code working without the `.resize()`, just the `.set_size_request()`.  Is this a lurking bug, or is it okay to skip the `.resize()` call?

**Comment by wmww** [comment]
If it works it works
