### ISSUE TITLE
Resizing a window stopped working

### ISSUE THREAD

**Issue by hraisins** [wmww/gtk-layer-shell#24]
I'm using gtk-layer-shell for a virtual keyboard project, Which has a window which is anchored left, bottom and right. Depending on circumstances (screen orientation, settings changes) I need to change the window height. This worked up to and including wmww/gtk-layer-shell@a20aeb57176f5cb49f0a4c267f76913ad62bc830 using (roughly) the following:

```
gtk_layer_set_exclusive_zone(window, new_height);
gtk_window_set_default_size(window, -1, new_height);
gtk_widget_queue_resize(GTK_WIDGET(window));
gtk_layer_auto_exclusive_zone_enable(window);
```

This no longer works, and I seem stuck on the initial window height. What's the new correct invocation to change the window height?

**Comment by ammen99** [comment]
I am no gtk-layer-shell expert, but can you try setting the window size request?

**Comment by hraisins** [comment]
That doesn't seem to work: first of all decreasing the size seems to do nothing, and increasing the size does affect the exclusive zone, and also the child is render larger, but partly offscreen (below the bottom of the screen). The actual size of the window seems unaffected. So there is some weirdness.

 BTW I landed on the above invocation through trail and error, the things I tried before that all had similar issues as described here.

**Comment by ammen99** [comment]
Another idea: try `gtk_window_resize` + setting the size request.

**Comment by hraisins** [comment]
Synthesized example: 
[layer-shell-resize.c.txt](https://github.com/wmww/gtk-layer-shell/files/3560235/layer-shell-resize.c.txt)

**Comment by wmww** [comment]
* wmww dives back into GTK resizing logic

**Comment by wmww** [comment]
(oops)

**Comment by wmww** [comment]
\* wmww dives back into GTK resizing logic

**Comment by wmww** [comment]
Thanks for the example, makes reproducing a lot easier. A few notes:
* In the compile command, I had to move `layer-shell-resize.c` to before the `$(pkg-config ...)` bits for some reason
* `gtk_layer_set_exclusive_zone()` is an alternative to `gtk_layer_auto_exclusive_zone_enable()`. Generally you'll either want to set the exclusive zone to zero, or enable auto exclusive zone and not touch it again. When auto exclusive zone is enabled, it will update itself whenever the window changes size (thus the "auto"). If you do need to manually set and update the exclusive zone for some reason, don't use `gtk_layer_auto_exclusive_zone_enable()`.

**Comment by hraisins** [comment]
That was my initial expectation (regarding _set_exclusive_zone and _auto_exclusive_zone_enable), but even with wmww/gtk-layer-shell@a20aeb5, if I remove one of the quartet of calls, it breaks over here. So, after fiddling with it for a while, when I found an invocation that reliably did what I wanted, I decided not to ask more questions and just move on.

**Comment by wmww** [comment]
Here is my lightly modified version of your file: https://gist.github.com/wmww/36ce9717116a4afe4223083c7b0963ee. I removed the extra auto exclusive zone calls (which in current context didn't give me any trouble) and switched to using `gtk_widget_set_size_request ()`, as is now required. Works for me in conjunction with #27.

**Comment by hraisins** [comment]
Ack. Passes all my initial tests, also in non-synthesized version. Thank you!

**Comment by wmww** [comment]
@hraisins Cool. How is your OSK going to talk to the compositor? I may be interested in throwing an implementation of whatever protocol you're using in Mir. Also, let me know if/when it becomes open source.

**Comment by ammen99** [comment]
@wmww Aren't there already standard protocols for OSKs? `wlr-virtual-keyboard` and `input-method`?

**Comment by hraisins** [comment]
Yes I'm using both those protocols, I don't have a public repo at the moment, but I plan on making one pretty soon (maybe this weekend, maybe next week). I'll let you know when it's available. Meanwhile you can look at [the competition](https://source.puri.sm/Librem5/squeekboard) which uses the same protocols.
