### ISSUE TITLE
Documentation comments not formatted for doc generator

### ISSUE THREAD

**Issue by wmww** [wmww/gtk-layer-shell#26]
Ideally we would run doxygen or something on at least gtk-layer-shell.h to generate documentation that's easier to read than the header itself. The comments are good, but I haven't formatted them for any sort of generator. It shouldn't be too hard, but I can't be bothered to figure out what the standard setup is for this sort of thing and do it. PRs welcome, or I'll probably get around to it sooner or later.

**Comment by hraisins** [comment]
I'll have a look at this (hopefully) next week.

**Comment by wmww** [comment]
Fixed by #28
