### ISSUE TITLE
[Question] Would a popover be considered a popup surface?

### ISSUE THREAD

**Issue by AdrianVovk** [wmww/gtk-layer-shell#3]
I'm planning on porting a shell I'm working on from a Wayfire-specific protocol to this library soon. My issue is, however, that layer-shell doesn't provide a way to have sane popover behavior (I can't have modal popovers because they don't let the user interact with the panel, and I don't get any unfocus signal when the user clicks outside the popover)

Anyway, I noticed that the menu popups with this library behave as I'd want them to. They'll close if the user interacts with anything outside of them, even with keyboard focus placed on the app. My question is this: would GtkPopover be treated the same way? I see you check for `transient_for`, and I'm unsure if GtkPopover sets this. Could you maybe add a popover into your demo program? Thank you!

**Comment by wmww** [comment]
Popovers seem to work fine. Added to demo here: https://github.com/wmww/gtk-layer-shell/commit/3efbbc356ea568ca2e3fbeccb8a3becf5fabf049.

**Comment by wmww** [comment]
Upon further investigation, it appears GTK popovers are implemented with subsurfaces instead of popups, which triggers a whole different set of flaky compositor behavior. For example, sway *does* show them, but doesn't give them input for some reason regardless of keyboard interactivity.
