### ISSUE TITLE
GTK module

### ISSUE THREAD

**Issue by vobie** [wmww/gtk-layer-shell#31]
Would it be possible to get layer shell functionality wrapped as an injectable GTK module? My reasoning is that it would allow one to place existing applications on the desired layer which would give people access to the whole GTK ecosystem of applications to utilize in their shell setup. Personally, I'm looking to use a webapp as desktop background without modifying and recompiling the entire browser which I'm not even sure I could manage on my own.

Thanks for putting time into wayland development, much appreciated!

**Comment by wmww** [comment]
I don't see why that wouldn't work. `[gtk_wayland_override_on_window_realize](https://github.com/wmww/gtk-layer-shell/blob/d1f9d94be32f8cc61c0a53af7558146570f0fa9f/src/gtk-wayland.c#L101)` already gets called every time a new window is opened, so you could stick some logic in there to set the layer on arbitrary windows without modifying the app that created them. No idea how to make a GTK module though, and probably wont work on that in the immediate future.

PRs welcome. I'm happy to advise on design, fix any newly exposed gtk-layer-shell, etc.

**Comment by wmww** [comment]
Doesn't seem like there's been any interest, and not something I plan to do at this time.
