### ISSUE TITLE
Disabling keyboard interactivity with OVERLAY or TOP layer does nothing 

### ISSUE THREAD

**Issue by wvffle** [wmww/gtk-layer-shell#32]
I'm trying to create overlay window but I ran into an issue where I have to disable keyboard interactivity while cursor is outside of the window.

I tried to use `leave-notify-event` and `enter-notify-event` for that:
```c
void window_leave (GtkWidget* widget, GdkEvent* event, gpointer* data) {
    printf("LEAVE\n");
    gtk_layer_set_keyboard_interactivity(GTK_WINDOW(window), FALSE);
}

void window_enter (GtkWidget* widget, GdkEvent* event, int* data) {
    printf("ENTER\n");
    gtk_layer_set_keyboard_interactivity(GTK_WINDOW(window), TRUE);
}
```

It seems to work for every layer type but `GTK_LAYER_SHELL_LAYER_TOP` and `GTK_LAYER_SHELL_LAYER_OVERLAY`. For those two the `key_press_event` is still firing even if the cursor is outside of the window.

**Comment by wmww** [comment]
I can reproduce, but looks to be a Sway or Wlroots bug. I reported it [here](https://github.com/swaywm/sway/issues/4840)
