### ISSUE TITLE
GIR & Vapi files

### ISSUE THREAD

**Issue by AdrianVovk** [wmww/gtk-layer-shell#5]
It'd be nice if this library shipped with GIR and vapi files so it can be easily used in different programming languages.

**Comment by wmww** [comment]
I don't know what those files are. From my initial research it appears Vapi files are specific to Vala, and GIR files are for GObject introspection. This library doesn't have any of its own GObjects, so presumably that would mean a GIR file is not relevant. Perhaps the Vapi file is. If anyone wants to use GTK Layer Shell in Vala, PRs welcome. Until then, I don't think not having them is an issue.

**Comment by myfreeweb** [comment]
vapi is not necessary, Vala converts GIR to vapi on the fly.

Having own GObjects is not a prerequisite, functions that operate on GtkWindow are very much covered of course.

With the Meson build system (#8), I've been able to set up `g-ir-scanner` easily.

<details><summary>`GtkLayerShell-0.1.gir` looks like this</summary>

```xml
<?xml version="1.0"?>
<!-- This file was automatically generated from C sources - DO NOT EDIT!
To affect the contents of this file, edit the original C definitions,
and/or use gtk-doc annotations.  -->
<repository version="1.2"
            xmlns="http://www.gtk.org/introspection/core/1.0"
            xmlns:c="http://www.gtk.org/introspection/c/1.0"
            xmlns:glib="http://www.gtk.org/introspection/glib/1.0">
  <include name="Gtk" version="3.0"/>
  <package name="gtk-layer-shell"/>
  <c:include name="gtk-layer-shell/gtk-layer-shell.h"/>
  <namespace name="GtkLayerShell"
             version="0.1"
             shared-library="libgtk-layer-shell.so"
             c:identifier-prefixes="GtkLayerShell"
             c:symbol-prefixes="gtk_layer">
    <enumeration name="Edge" c:type="GtkLayerShellEdge">
      <source-position filename="../include/gtk-layer-shell.h" line="22"/>
      <member name="left" value="0" c:identifier="GTK_LAYER_SHELL_EDGE_LEFT">
      </member>
      <member name="right" value="1" c:identifier="GTK_LAYER_SHELL_EDGE_RIGHT">
      </member>
      <member name="top" value="2" c:identifier="GTK_LAYER_SHELL_EDGE_TOP">
      </member>
      <member name="bottom"
              value="3"
              c:identifier="GTK_LAYER_SHELL_EDGE_BOTTOM">
      </member>
      <member name="entry_number"
              value="4"
              c:identifier="GTK_LAYER_SHELL_EDGE_ENTRY_NUMBER">
      </member>
    </enumeration>
    <enumeration name="Layer" c:type="GtkLayerShellLayer">
      <source-position filename="../include/gtk-layer-shell.h" line="14"/>
      <member name="background"
              value="0"
              c:identifier="GTK_LAYER_SHELL_LAYER_BACKGROUND">
      </member>
      <member name="bottom"
              value="1"
              c:identifier="GTK_LAYER_SHELL_LAYER_BOTTOM">
      </member>
      <member name="top" value="2" c:identifier="GTK_LAYER_SHELL_LAYER_TOP">
      </member>
      <member name="overlay"
              value="3"
              c:identifier="GTK_LAYER_SHELL_LAYER_OVERLAY">
      </member>
      <member name="entry_number"
              value="4"
              c:identifier="GTK_LAYER_SHELL_LAYER_ENTRY_NUMBER">
      </member>
    </enumeration>
    <function name="auto_exclusive_zone_enable"
              c:identifier="gtk_layer_auto_exclusive_zone_enable">
      <source-position filename="../include/gtk-layer-shell.h" line="61"/>
      <return-value transfer-ownership="none">
        <type name="none" c:type="void"/>
      </return-value>
      <parameters>
        <parameter name="window" transfer-ownership="none">
          <type name="Gtk.Window" c:type="GtkWindow*"/>
        </parameter>
      </parameters>
    </function>
    <function name="init_for_window" c:identifier="gtk_layer_init_for_window">
      <source-position filename="../include/gtk-layer-shell.h" line="27"/>
      <return-value transfer-ownership="none">
        <type name="none" c:type="void"/>
      </return-value>
      <parameters>
        <parameter name="window" transfer-ownership="none">
          <type name="Gtk.Window" c:type="GtkWindow*"/>
        </parameter>
      </parameters>
    </function>
    <function name="set_anchor" c:identifier="gtk_layer_set_anchor">
      <source-position filename="../include/gtk-layer-shell.h" line="50"/>
      <return-value transfer-ownership="none">
        <type name="none" c:type="void"/>
      </return-value>
      <parameters>
        <parameter name="window" transfer-ownership="none">
          <type name="Gtk.Window" c:type="GtkWindow*"/>
        </parameter>
        <parameter name="edge" transfer-ownership="none">
          <type name="Edge" c:type="GtkLayerShellEdge"/>
        </parameter>
        <parameter name="anchor_to_edge" transfer-ownership="none">
          <type name="gboolean" c:type="gboolean"/>
        </parameter>
      </parameters>
    </function>
    <function name="set_exclusive_zone"
              c:identifier="gtk_layer_set_exclusive_zone">
      <source-position filename="../include/gtk-layer-shell.h" line="60"/>
      <return-value transfer-ownership="none">
        <type name="none" c:type="void"/>
      </return-value>
      <parameters>
        <parameter name="window" transfer-ownership="none">
          <type name="Gtk.Window" c:type="GtkWindow*"/>
        </parameter>
        <parameter name="exclusive_zone" transfer-ownership="none">
          <type name="gint" c:type="int"/>
        </parameter>
      </parameters>
    </function>
    <function name="set_keyboard_interactivity"
              c:identifier="gtk_layer_set_keyboard_interactivity">
      <source-position filename="../include/gtk-layer-shell.h" line="65"/>
      <return-value transfer-ownership="none">
        <type name="none" c:type="void"/>
      </return-value>
      <parameters>
        <parameter name="window" transfer-ownership="none">
          <type name="Gtk.Window" c:type="GtkWindow*"/>
        </parameter>
        <parameter name="interacitvity" transfer-ownership="none">
          <type name="gboolean" c:type="gboolean"/>
        </parameter>
      </parameters>
    </function>
    <function name="set_layer" c:identifier="gtk_layer_set_layer">
      <source-position filename="../include/gtk-layer-shell.h" line="39"/>
      <return-value transfer-ownership="none">
        <type name="none" c:type="void"/>
      </return-value>
      <parameters>
        <parameter name="window" transfer-ownership="none">
          <type name="Gtk.Window" c:type="GtkWindow*"/>
        </parameter>
        <parameter name="layer" transfer-ownership="none">
          <type name="Layer" c:type="GtkLayerShellLayer"/>
        </parameter>
      </parameters>
    </function>
    <function name="set_margin" c:identifier="gtk_layer_set_margin">
      <source-position filename="../include/gtk-layer-shell.h" line="55"/>
      <return-value transfer-ownership="none">
        <type name="none" c:type="void"/>
      </return-value>
      <parameters>
        <parameter name="window" transfer-ownership="none">
          <type name="Gtk.Window" c:type="GtkWindow*"/>
        </parameter>
        <parameter name="edge" transfer-ownership="none">
          <type name="Edge" c:type="GtkLayerShellEdge"/>
        </parameter>
        <parameter name="margin_size" transfer-ownership="none">
          <type name="gint" c:type="int"/>
        </parameter>
      </parameters>
    </function>
    <function name="set_monitor" c:identifier="gtk_layer_set_monitor">
      <source-position filename="../include/gtk-layer-shell.h" line="44"/>
      <return-value transfer-ownership="none">
        <type name="none" c:type="void"/>
      </return-value>
      <parameters>
        <parameter name="window" transfer-ownership="none">
          <type name="Gtk.Window" c:type="GtkWindow*"/>
        </parameter>
        <parameter name="monitor" transfer-ownership="none">
          <type name="Gdk.Monitor" c:type="GdkMonitor*"/>
        </parameter>
      </parameters>
    </function>
    <function name="set_namespace" c:identifier="gtk_layer_set_namespace">
      <source-position filename="../include/gtk-layer-shell.h" line="34"/>
      <return-value transfer-ownership="none">
        <type name="none" c:type="void"/>
      </return-value>
      <parameters>
        <parameter name="window" transfer-ownership="none">
          <type name="Gtk.Window" c:type="GtkWindow*"/>
        </parameter>
        <parameter name="name_space" transfer-ownership="none">
          <type name="utf8" c:type="const char*"/>
        </parameter>
      </parameters>
    </function>
  </namespace>
</repository>
```

</details>

Tested with Python:

```python
import gi
gi.require_version("Gtk", "3.0")
gi.require_version("GtkLayerShell", "0.1")
from gi.repository import Gtk, GtkLayerShell

window = Gtk.Window()
GtkLayerShell.init_for_window(window)
GtkLayerShell.auto_exclusive_zone_enable(window)
GtkLayerShell.set_margin(window, GtkLayerShell.Edge.TOP, 10)
GtkLayerShell.set_anchor(window, GtkLayerShell.Edge.LEFT, 1)
GtkLayerShell.set_anchor(window, GtkLayerShell.Edge.BOTTOM, 1)
GtkLayerShell.set_anchor(window, GtkLayerShell.Edge.RIGHT, 1)
window.show()
window.connect("destroy", Gtk.main_quit)
Gtk.main()
```

And Vala:

```vala
using Gtk;
using GtkLayerShell;

int main (string[] args) {
	Gtk.init (ref args);
	var window = new Window ();
	GtkLayerShell.init_for_window(window);
	GtkLayerShell.auto_exclusive_zone_enable(window);
	GtkLayerShell.set_margin(window, GtkLayerShell.Edge.TOP, 10);
	GtkLayerShell.set_anchor(window, GtkLayerShell.Edge.LEFT, true);
	GtkLayerShell.set_anchor(window, GtkLayerShell.Edge.BOTTOM, true);
	GtkLayerShell.set_anchor(window, GtkLayerShell.Edge.RIGHT, true);
	window.destroy.connect (Gtk.main_quit);
	window.show ();
	Gtk.main ();
	return 0;
}
```

`valac --pkg gtk+-3.0 --pkg GtkLayerShell-0.1 test.vala && ./test`

**Comment by properlypurple** [comment]
Adding the dependency `dependency('gtk-layer-shell-0', required: true)`  to meson.build fails with this error still, so it probably needs some other fix as well

````
valac -C --debug --debug --target-glib=2.38 --pkg gtk-layer-shell-0 --pkg gobject-2.0 --pkg gtk+-3.0 --pkg glib-2.0 --color=always --directory src/avizo-service.p --basedir ../src --gresources=../avizo.gresource.xml ../src/avizo_service.vala
error: Package `gtk-layer-shell-0' not found in specified Vala API directories or GObject-Introspection GIR directories
````

**Comment by myfreeweb** [comment]
@properlypurple hm, meson has generated `--pkg gtk-layer-shell-0` (using the pkgconf-style name) but as you can see from my post above, what works is `--pkg GtkLayerShell-0.1` (using the GIR name).

Looks like the reason stuff like `--pkg gtk+-3.0` works is that Vala itself is shipped with `vapi` files that have these names.
We could ship a `vapi` but I don't like that: if `valac` can consume `gir` on its own, why should vala get this special treatment in every gobject library :P

Try adding `vala_args: ['--pkg GtkLayerShell-0.1']` to your target, and not including the dependency in its dependencies.

**Comment by wmww** [comment]
@myfreeweb that's not working for me. First of all, it needs to be `'--pkg=GtkLayerShell-0.1'` (note the `=`), but more importantly I'm getting undefined reference errors. It seems to be finding the header, but not trying to actually link against the library. My meson.build looks like the following, with your example vala code in `app.vala`:

```meson
project('vala-layer-shell',
    ['vala', 'c'],
    version: '0.1.0',
    license: 'MIT',
    meson_version: '>=0.45.1')

executable(
    'app',
    files('app.vala'),
    vala_args: ['--pkg=GtkLayerShell-0.1'],
    dependencies: [dependency('gtk+-3.0')])
```

**Comment by properlypurple** [comment]
@myfreeweb Thank you for responding. Adding `vala_args: ['--pkg GtkLayerShell-0.1']` to my build target fails with 

````
FAILED: src/avizo-service.p/avizo_service.c 
valac -C --debug --debug --target-glib=2.38 --vapidir /home/properlypurple/Projects/avizo --pkg gobject-2.0 --pkg gtk+-3.0 --pkg glib-2.0 --color=always --directory src/avizo-service.p --basedir ../src --gresources=../avizo.gresource.xml '--pkg GtkLayerShell-0.1' ../src/avizo_service.vala
Unknown option --pkg GtkLayerShell-0.1
Run 'valac --help' to see a full list of available command line options.
ninja: build stopped: subcommand failed.
````

I was able to generate a vapi manually, and adding that to the project, so it might be okay for now.

**Comment by wmww** [comment]
I've spent a number of hours today poking at this, but I don't feel like I'm making much progress. PR's more than welcome for anything that makes it easier to use with Vala or documents how to do it, but so far I've had the least luck of anyone here getting it to work, so I will not be the one to write them.

**Comment by myfreeweb** [comment]
> not trying to actually link against the library

Oh, meson actually does linking on its own and that would need a dependency in the `dependencies` section. But if we have that it would also pass the `--pkg` flag to vala. Welp, meson's inflexibility strikes again >_< There's really no good way to use valac's direct support for gir files from meson.

> anything that makes it easier to use with Vala

You could [`generate_vapi`](https://mesonbuild.com/Gnome-module.html#gnomegenerate_vapi) here if you do think Vala(+meson) deserves that special treatment from every package like that.

**Comment by properlypurple** [comment]
This looks like it's relevant
https://github.com/mesonbuild/meson/issues/4481

**Comment by myfreeweb** [comment]
Rather, this: https://github.com/mesonbuild/meson/issues/1195

There is an interesting suggestion to use `generate_vapi` in the consumer (the vala app) but I don't see how that would handle the linking. `generate_vapi` does *return* a dependency, but it doesn't *take* the pkg-config one. Maybe it does pick it up from `<package>` in the gir though. @properlypurple have you tried generating using the meson function rather than manually?

**Comment by properlypurple** [comment]
Ah yes. Thank you @myfreeweb .

I actually didn't try that. In fact, it was a forked project I was trying to add layer shell to, and now I'm thinking of rewriting the whole thing in Python.

**Comment by astavale** [comment]
From what I can tell your `pkg-config` file for the C library is called `gtk-layer-shell.pc` and the GIR name is different, so the all in one `dependency()` is having problems with file name resolution. For complex set ups the answer, I think, is to split up `dependency()` and use each compiler's `find_libary()` method.

Can someone try this in their meson.build file:

```
project('vala-layer-shell',
    ['vala', 'c'],
    version: '0.1.0',
    license: 'MIT',
    meson_version: '>=0.45.1')

executable(
    'app',
    files('app.vala'),
    meson.get_compiler('vala').find_library('GtkLayerShell-0.1'),
    meson.get_compiler('c').find_library('gtk-layer-shell')
    dependencies: [dependency('gtk+-3.0')]
)
```
If that fails then try:
```
project('vala-layer-shell',
    ['vala', 'c'],
    version: '0.1.0',
    license: 'MIT',
    meson_version: '>=0.45.1')

executable(
    'app',
    files('app.vala'),
    vala_args: ['--pkg','GtkLayerShell-0.1'],
    meson.get_compiler('c').find_library('gtk-layer-shell')
    dependencies: [dependency('gtk+-3.0')]
)
```


Another option is to generate a VAPI at build time using Meson:

```
project('vala-layer-shell',
    ['vala', 'c'],
    version: '0.1.0',
    license: 'MIT',
    meson_version: '>=0.45.1')

executable(
    'app',
    files('app.vala'),
    gnome.generate_vapi('gtk-layer-shell', 'GkLayerShell-0.1'),
    meson.get_compiler('c').find_library('gtk-layer-shell')
    dependencies: [dependency('gtk+-3.0')]
)
```
Not sure about the file path for GtkLayerShell-0.1 for that one.

**Comment by myfreeweb** [comment]
> find_library

That's definitely a problem because `find_library` only looks at the default search path, avoiding pkg-config completely. Won't fly on FreeBSD where installed packages are in `/usr/local` which is not on the default search path. (Probably even worse on NixOS?)

We do need the `dependency('gtk-layer-shell-0')` via pkg-config for the "C" (linking) part.

**Comment by astavale** [comment]
> We do need the `dependency('gtk-layer-shell-0')` via pkg-config for the "C" (linking) part.

OK, well have you tried `dependency('gtk-layer-shell', language: 'c')`?  See [`dependency()`](https://mesonbuild.com/Reference-manual.html#dependency)

Is your pkg-config file really called `gtk-layer-shell-0.pc`?

**Comment by myfreeweb** [comment]
That does not work, was this ever implemented?

```
../meson.build:3:0: ERROR: gtk-layer-shell-0 dependency does not accept "language" keyword argument
```

> Is your pkg-config file really called gtk-layer-shell-0.pc?

Yes, why is that surprising? Versioned files are the usual convention now, because it makes multiple ABI-breaking versions parallel-installable.

```
% ls /usr/local/libdata/pkgconfig | rg "\-[\d\.]+"
[..]
gck-1.pc
gconf-2.0.pc
gcr-3.pc
gcr-base-3.pc
gcr-ui-3.pc
gdk-2.0.pc
gdk-3.0.pc
[..]
```

**Comment by wmww** [comment]
I've got the magic incantation. We had all the pieces, but nobody seems to have put them together quite right (or if they did, it got lost in the noise).

```meson
project('vala-layer-shell',
    ['vala', 'c'],
    version: '0.1.0',
    license: 'MIT',
    meson_version: '>=0.45.1')

executable(
    'app',
    files('app.vala'),
    vala_args: ['--pkg=GtkLayerShell-0.1'],
    dependencies: [
        dependency('gtk+-3.0'),
        meson.get_compiler('c').find_library('gtk-layer-shell')])
```

I will be adding a Vala example to the examples directory (and CI) shortly.

Some notes:
- Why does `find_library()` on the C compiler need to be `gtk-layer-shell` instead of `gtk-layer-shell-0`? I do not know, but it does.
- astavale's last example mistaking calls the library `GkLayerShell-0.1` (missing `t`). Beware when copy-pasting
- `meson.get_compiler('vala').find_library('GtkLayerShell-0.1')` does not work because meson tries to compile a sample file with `--pkg GtkLayerShell-0.1`, which fails because it also requires `--pkg gtk+-3.0`. There doesn't seem to be a way to specify a dependency or command-line override for `find_library()`. If there is a way to specify a dependency in a `.gir` file and have meson respect that I have not found it.
- We may want to generate a vapi in the library to make things easier going forward

**Comment by myfreeweb** [comment]
@wmww please read https://github.com/wmww/gtk-layer-shell/issues/5#issuecomment-733010853

> Why does find_library() on the C compiler need to be gtk-layer-shell instead of gtk-layer-shell-0?

because `find_library` **does not use pkg-config**, it's basically like probing `cc -lYOUR_NAME`, and it will EXPLODE if the library is only findable via pkg-config.

**Comment by wmww** [comment]
Good to know. By the way @myfreeweb, can I get explicit permission to license code derived from your Vala and Python examples as MIT?

**Comment by myfreeweb** [comment]
Yes, you can license as anything, don't want any name on them. These examples, I'm not even sure they would be copyrightable at all, they don't contain any significant algorithms, they basically list your API :D

**Comment by AdrianVovk** [comment]
Whoops I must have fallen off the face of the planet for a while here. Today I thought "I wonder if gtk-layer-shell ever got around to implementing the Vapi file I opened an issue for" and turns out: eh sorta

> You could [`generate_vapi`](https://mesonbuild.com/Gnome-module.html#gnomegenerate_vapi) here if you do think Vala(+meson) deserves that special treatment from every package like that.

That is the intended & correct way to do things. Vala wants VAPI files because GIR translation is (99% of the time) unreliable: GIR doesn't support all of valac's features, so often Vala will lose important details in the GIR. Look at [all](https://gitlab.com/carbonOS/os-updated/-/blob/master/build-aux/vapi-metadata/OSTree-1.0.metadata) the [postprocessing](https://gitlab.com/carbonOS/os-updated/-/blob/master/build-aux/vapi-metadata/ostree-custom.vala) I [have to do](https://gitlab.com/carbonOS/os-updated/-/blob/d0b6cf9a/build-aux/update-vapi) to get a semi-functional `ostree` vapi from the Gir. For your library's simple API, using the GIR directly happens to work. But it still breaks the hell out of meson

The magic meson incantation you're doing is a hack and honestly just kinda ugly. Also it's not scalable: some of my projects link to gtk-layer-shell many times (5+ times, in the case of `gde-dialogs`). I don't want to pass arguments directly to the vala compiler for every binary I link because that's what meson provides dependencies for.

For now, I'll either keep copying around the VAPI file I've had local to each project using gtk-layer-shell, or just generate one for my distro's package outside of your build system. Ideally, of course, you could call generate_vapi in meson and everything would just work as intended

**Comment by wmww** [comment]
Not my area of expertise. PRs continue to be welcome.
