### ISSUE TITLE
Demo intermittently crashes on popover update

### ISSUE THREAD

**Issue by wmww** [wmww/gtk-layer-shell#51]
Possibly related to #47

To reproduce:
- Open gtk-layer-demo
- Open the "set margin" popover
- Play around with it a little (close and re-run gtk-layer-demo if nothing happens)
- Eventually you will see:
```
../../../../src/cairo-surface.c:930: cairo_surface_reference: Assertion `CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&surface->ref_count)' failed.
```

When gtk-layer-demo is passed `--no-layer-shell`, neither the flicker described in #47 or this happens, indicating it's definitly a gtk-layer-shell problem.

NOTE: this happens on Sway, but doesn't appear to effect gtk-layer-demo running on Mir. This is strange.

**Comment by wmww** [comment]
It appears both this and #47 are indirectly caused by us committing our shared `wl_surface` when GTK doesn't expect it. We seem to be committing after GTK has attached a buffer but before GTK has committed it. This leads the compositor to release that buffer while GTK thinks it's still uncommitted and all hell breaks loose. Still working on the ideal solution.

**Comment by alebastr** [comment]
@wmww does this deserve a patch release (0.2.1) or there's something else you want to address before that?
I don't see the crash on any apps other than gtk-layer-demo but this might just mean that I'm lucky enough.

**Comment by wmww** [comment]
I want to investigate #47 more and possibly add some other stuff before a release. That should happen within a week or two.
